.\" noose.1
.\" Copyright 2001 Julian E. C. Squires (tek@wiw.org)
.\" $Id$
.\" 
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" 
.TH NOOSE 1 "22 Apr 2001" ""
.SH NAME
noose \- a command-line NNTP tool
.SH SYNOPSIS
.B noose
[\fIOPTION\fR]... <\fICOMMAND\fR>
.SH DESCRIPTION
.PP
.B noose
is a command-line tool which can check for new posts
on a news server, via NNTP, in the groups to which one is subscribed, or
read articles by article-number.
.SH OPTIONS
.TP
\fB\-q\fR
Be less verbose in output. This is most commonly used to make the \fBcheck\fR
command only output groups with non-zero unread messages present.
.TP
\fB\-v\fR
Be more verbose in output.
.TP
\fB\-n\fR \fIserver\fR
Use \fIserver\fR as the NNTP server. By default, the value of the
environment variable NNTPSERVER is used, and if it is not present,
just "news" is used.
.TP
\fB\-r\fR \fIrcfile\fR
Use \fIrcfile\fR as the newsrc file. This is only necessary when using
the \fBcheck\fR command. By default, $HOME/.jnewsrc and $HOME/.newsrc
will be tried, in that order.
.SH COMMANDS
.TP
\fBcheck\fR [\fIgroup\fR]
Returns how many unread posts are in all subscribed groups, or just
\fIgroup\fR, if specified.
.TP
\fBread\fR [\fIgroup\fR] <\fIn\fR>
Grab the entirity of article \fIn\fR from \fIgroup\fR.
.SH AUTHOR
Julian Squires <tek@wiw.org>

